// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_tOtWTewn-IoY4pG6HzB9tRQYL2I6YDo',
    appId: '1:931794016260:web:33454c6a8c4273bf473d51',
    messagingSenderId: '931794016260',
    projectId: 'checkmate-6e989',
    authDomain: 'checkmate-6e989.firebaseapp.com',
    storageBucket: 'checkmate-6e989.firebasestorage.app',
    measurementId: 'G-G2STK5YYNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHXFdk5CNPsS7gGcmrzsFOqu1rajTqh1Q',
    appId: '1:931794016260:android:8fbb912156d102ed473d51',
    messagingSenderId: '931794016260',
    projectId: 'checkmate-6e989',
    storageBucket: 'checkmate-6e989.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTVfGq3_1TyDJGqbhtMQMexcy_tXmCQvc',
    appId: '1:931794016260:ios:3c23d3af1b9ee45f473d51',
    messagingSenderId: '931794016260',
    projectId: 'checkmate-6e989',
    storageBucket: 'checkmate-6e989.firebasestorage.app',
    iosClientId: '931794016260-usofrrr7f7eqhnaplpi7co8bisa1drod.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTVfGq3_1TyDJGqbhtMQMexcy_tXmCQvc',
    appId: '1:931794016260:ios:3c23d3af1b9ee45f473d51',
    messagingSenderId: '931794016260',
    projectId: 'checkmate-6e989',
    storageBucket: 'checkmate-6e989.firebasestorage.app',
    iosClientId: '931794016260-usofrrr7f7eqhnaplpi7co8bisa1drod.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_tOtWTewn-IoY4pG6HzB9tRQYL2I6YDo',
    appId: '1:931794016260:web:6f9e5494807c8766473d51',
    messagingSenderId: '931794016260',
    projectId: 'checkmate-6e989',
    authDomain: 'checkmate-6e989.firebaseapp.com',
    storageBucket: 'checkmate-6e989.firebasestorage.app',
    measurementId: 'G-SDSQY3PZGW',
  );

}